name: ccgkoeln deployment

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.71.1'

    - name: Build
      run: hugo --minify

    - name: Push Public
      run: |
        cd public
        git checkout master
        git config --local user.email "mingyizhang1987@gmail.com"
        git config --local user.name "Mingyi Zhang"
        git add .
        git commit -m "Test deploy from github action"
        git push
