name: ccgkoeln deployment

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.71.1'

    - name: Build
      run: hugo --minify

    - name: Push Public
      run: |
        cd public
        git config --local user.email "mingyizhang1987@gmail.com"
        git config --local user.name "Mingyi Zhang"
        git add .
        git commit -m "test deploy in github action"
        git push